name: flutter_pvstate
description: Extremely lightweight state management framework in only 90 lines of code.
version: 0.1.0
anthor: hackware
homepage: https://github.com/hackware1993/Flutter_PVState

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_constraintlayout: ^1.6.3-stable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
